data:
  root_dir: "dataset/vehicle-x"

model:
  input_dims: 2071
  output_dims: 1363
  BDNN:
    mlp_layers: [ 4096, 2048 ]
    do_BN: False
    dropout: 0.0

train:
  task: BDNN
  batch_size: 1024
  num_workers: 2
  optimizer: SGD
  learning_rate: 0.05
  momentum: 0.9
  epochs: 150
  save_dir: "checkpoint"

test:
  model_dir: "checkpoint"
  task: BDNN
  test_top_1: True
  test_top_5: True