data:
  root_dir: "dataset/vehicle-x"

model:
  input_dims: 2071
  output_dims: 1362
  baseline:
    mlp_layers: [2048, 2048, 1532]
    do_BN: False
    dropout: 0.0

train:
  task: baseline
  batch_size: 1024
  num_workers: 2
  optimizer: SGD
  learning_rate: 0.1
  momentum: 0.9
  epochs: 150
  save_dir: "checkpoint"

test:
  model_dir: "checkpoint"
  task: baseline
  test_top_1: True
  test_top_5: True